---
title: "Casos & Óbitos por COVID-19 na cidade de Rio de Janeiro"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})

output: html_document


---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=4, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```



Gráficos montados a partir de dados que o https://brasil.io compila.


Dados de 28 de junho de 2020.

Pontos para cada dia, assim como uma linha de tendência feita por ["amaciamento de médias"](https://ggplot2.tidyverse.org/reference/geom_smooth.html) (*Smoothed conditional means*).

Aviso: os dados de fim de semana são comumente subestimados. O fim da curva de amaciamento de médias é influenciado por esses pontos. 


```{r, limpando, echo=FALSE}
library(httr)
library(jsonlite)
library(dplyr)
library(tidyr)

res = GET("https://brasil.io/api/dataset/covid19/caso_full/data/?search=&date=&state=&city=Rio+de+Janeiro&place_type=&is_last=&city_ibge_code=&order_for_place=")
data = fromJSON(rawToChar(res$content))
dados_rj = data[["results"]]
write.csv(dados_rj, "dados_rj_hj.csv")

# dados_rj = read.csv("dados_rj_hj.csv")


dados_rj_selecionada = dados_rj %>% select(c("date", "last_available_confirmed", "last_available_deaths", "order_for_place"))

colnames(dados_rj_selecionada) = c("Data", "Casos Confirmados Cumulativos", "Óbitos Confirmados Cumulativos", "Dia de contagem")
library(ggplot2)
library(plotly)


dados_rj_selecionada["Casos por dia"] <- c(-(diff(dados_rj_selecionada[,"Casos Confirmados Cumulativos"])),0)
dados_rj_selecionada["Óbitos Confirmados por dia"] <- c(-(diff(dados_rj_selecionada[,"Óbitos Confirmados Cumulativos"])),0)

```


```{r ajustando o tempo}
library(lubridate)

dados_rj_selecionada <- dados_rj_selecionada[complete.cases(dados_rj_selecionada), ]

dados_rj_selecionada["Data"] <- as.Date(ymd(dados_rj_selecionada[["Data"]]))
```

```{r reshapando a tabela}
dados_rj_selecionada_long <- pivot_longer(dados_rj_selecionada, 
                                         cols = c("Casos Confirmados Cumulativos", "Óbitos Confirmados Cumulativos", "Casos por dia", "Óbitos Confirmados por dia"),
                                         names_to = "Tipo",
                                         values_to = "Contagem")

```


```{r preparando figura}

gerar_plot <- function(tabela_de_casos, titulo, rotulo_eixo_x, ref_cores){
  p1 = ggplot(tabela_de_casos, aes(x=Data,
                          y = Contagem,
                          color = Tipo))    + 
  geom_point(size = 1) + 
  geom_smooth(size=2) +  
  ggtitle(titulo)+
  xlab(rotulo_eixo_x)+ 
  labs(caption = "Fonte: Dados consolidados por Brasil IO a partir dos boletins da prefeitura ")  +       
  
  scale_discrete_manual(aesthetics = c("color"), drop=TRUE, values= c( "gold4", "gold3", "firebrick4", "firebrick3" ),
        limits = levels(ref_cores))
  return(p1)
}

```



## Casos de COVID-19 por dia

```{r}

classes_para_cor <- factor(dados_rj_selecionada_long$Tipo)

dados_rj_selecionada_long["Data"] <- as.Date(dados_rj_selecionada_long[["Data"]])
so_casos <- dados_rj_selecionada_long %>% filter(`Tipo` %in% c("Casos Confirmados Cumulativos", "Casos por dia"))

titulo_casos = "Casos confirmados de COVID-19 na cidade de Rio de Janeiro"


ultima_data = dados_rj_selecionada_long[["Data"]][1]
rotulo_eixo_x = paste0('Contagem', " (até ", ultima_data, ")")

p1 = gerar_plot(so_casos, titulo_casos, rotulo_eixo_x, ref_cores = classes_para_cor)

ggplotly(p1, tooltip = c("Contagem", "Data"))
```

```{r}
so_casos_por_dia <- dados_rj_selecionada_long %>% filter(`Tipo` %in% c("Casos por dia"))

p2 = gerar_plot(so_casos_por_dia, titulo_casos, rotulo_eixo_x, ref_cores = classes_para_cor)

ggplotly(p2, tooltip = c("Contagem", "Data"))
```


## Óbitos por COVID-19 por dia

```{r}
so_obitos <- dados_rj_selecionada_long %>% filter(`Tipo` %in% c("Óbitos Confirmados Cumulativos", "Óbitos Confirmados por dia"))


titulo_obitos = "Óbitos confirmados por COVID-19 na cidade de Rio de Janeiro"

p3 = gerar_plot(so_obitos, titulo_obitos, rotulo_eixo_x, ref_cores = classes_para_cor)
ggplotly(p3, tooltip = c("Contagem", "Data"))

```


```{r}
so_obitos_diarios <- dados_rj_selecionada_long %>% filter(`Tipo` %in% c("Óbitos Confirmados por dia"))

p4 = gerar_plot(so_obitos_diarios, titulo_obitos, rotulo_eixo_x, ref_cores = classes_para_cor)
ggplotly(p4, tooltip = c("Contagem", "Data"))
```


